### ISSUE TITLE
how to build?

### ISSUE THREAD

**Issue by 0xfocu5** [tlspuffin/tlspuffin#227]
hi i found some bugs like this:

git clone git@github.com/tlspuffin/tlspuffin
fatal: repository 'git@github.com/tlspuffin/tlspuffin' does not exist

so, i git clone the project by : git clone https://github.com/tlspuffin/tlspuffin.git

but, when i build it, i got some errors:
error: failed to load source for dependency `openssl-src`

Caused by:
  Unable to update /home/autumn/Desktop/work/fuzz/fuzzTools/tls/tlspuffin/crates/openssl-src-111

Caused by:
  failed to read `/home/autumn/Desktop/work/fuzz/fuzzTools/tls/tlspuffin/crates/openssl-src-111/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

how to solve this? thanks, and sorry for my bad english.

**Comment by maxammann** [comment]
I think you will need to pull the submodules:

`git submodule update --init --recursive`

**Comment by 0xfocu5** [comment]
thanks a lot , i solved it , by the way, readme 's building needs to update
git clone git@github.com/tlspuffin/tlspuffin ---->git@github.com:tlspuffin/tlspuffin.git
git submodule update --init --recursive
cargo build

**Comment by maxammann** [comment]
Thx, updated!
